# Generated by Django 4.1.7 on 2023-04-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_oder_order_rename_oder_item_order_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_add',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
